name: Publish Docker release image

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-release-package:
    name: Build and release package
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/build.yml
        name: Lint and build the project

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: ncipollo/release-action@v1
        with:
          artifacts: dist/*.tar.gz
          token: ${{ secrets.GITHUB_TOKEN }}

  build-release-docker:
    name: Build and publish Docker image
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v3
        name: Check out the repository

      - uses: docker/login-action@v2
        name: Log in to the container registry
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/metadata-action@v4
        name: Extract metadata (tags, labels) for Docker
        id: meta-arm64
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{ version }},suffix=-arm64
            latest-arm64

      - uses: docker/build-push-action@v4
        name: Build and push the Docker arm64 image
        with:
          context: .
          file: ./Dockerfile-arm64v8
          push: true
          tags: ${{ steps.meta-arm64.outputs.tags }}
          labels: ${{ steps.meta-arm64.outputs.labels }}

      - uses: docker/metadata-action@v4
        name: Extract metadata (tags, labels) for Docker
        id: meta
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{ version }}
            latest

      - uses: docker/build-push-action@v4
        name: Build and push the Docker image
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}